# Generated by Django 3.0.5 on 2020-05-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200506_1133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='business',
            unique_together={('name', 'industry', 'city')},
        ),
    ]
