# Generated by Django 3.0.5 on 2020-05-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200506_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='keyword',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
