# Generated by Django 3.0.5 on 2020-05-07 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_business_keyword'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='business',
            unique_together={('name', 'industry', 'city', 'keyword')},
        ),
    ]
