# Generated by Django 3.0.5 on 2020-05-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200507_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
