# Generated by Django 3.0.5 on 2020-05-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_business_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='postalcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
