# Generated by Django 3.0.5 on 2020-05-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_business_postalcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='business',
            unique_together={('name', 'industry', 'city', 'keyword', 'postalcode')},
        ),
    ]
