# Generated by Django 3.0.4 on 2020-05-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
