# Generated by Django 3.0.4 on 2020-05-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_orders_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderDate',
            field=models.DateField(blank=True, max_length=555, null=True),
        ),
    ]
