# Generated by Django 3.0.4 on 2020-05-22 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_orders_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateField(default=datetime.date(2020, 5, 22)),
        ),
    ]
