# Generated by Django 3.0.4 on 2020-05-22 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20200522_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.IntegerField(blank=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 22, 13, 0, 36, 292705, tzinfo=utc)),
        ),
    ]
