# Generated by Django 3.0.4 on 2020-05-25 16:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20200522_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderDate',
            field=models.DateField(default=datetime.datetime(2020, 5, 25, 16, 41, 52, 563497, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='business',
            unique_together={('name',)},
        ),
    ]
